region: ap-northeast-2

function_name: aws-ecs-task-rebalancer
handler: service.handler
description: aws-ecs task rebalancer.
runtime: python3.6
timeout: 180
memory_size: 128

# S3 upload requires appropriate role with s3:PutObject permission
# (ex. basic_s3_upload), a destination bucket, and the key prefix
# bucket_name: 'example-bucket'
# s3_key_prefix: 'path/to/file/'

aws_access_key_id:
aws_secret_access_key:
role: ECS-LambdaExecuteRoleForTaskRebalance

dist_directory: dist

# Build options
# build:
#   # a comma delimited list of directories in your project root that contains source to package.
#   source_directories: utils
